### ISSUE TITLE
There is a print() statement left in the code probably for debugging

### ISSUE THREAD

**Issue by archatas** [websideproject/paddle-billing-client#162]
## 🐛 Bug Report

The calls to the API always spits out debugging information.

## 🔬 How To Reproduce

1. Call any API function for the client, e.g. `client.list_products()`

### Code sample

```python
class Endpoints:
    def __init__(self, base_url="https://sandbox-api.paddle.com"):
        self._base_url = base_url

    def __getattribute__(self, name):
        print(name)
        # ...
```

The print statement should be removed or executed optionally based on some debug parameter.

### Environment

* OS: macOS
* Python 3.10

**Comment by bgervan** [comment]
Fixed with https://github.com/websideproject/paddle-billing-client/pull/163
