### ISSUE TITLE
The delivered_at and last_attempt_at dates must be nullable for Notifications

### ISSUE THREAD

**Issue by archatas** [websideproject/paddle-billing-client#184]
## 🐛 Bug Report

When trying to retrieve notifications with `client.list_notifications()` validation errors might occur if there are still undelivered notifications because of any bugs in the webhook page.

## 🔬 How To Reproduce

1. Create a webhook page that raises a server error.
2. Create a notification setting reporting to that webhook
3. Trigger a notification by changing anything at Paddle sandbox
4. Try to list notifications using `client.list_notifications()`

### Code sample

According to the docs, the delivered_at and last_attempt_at fields might be null. The Notification model definition must be changed.
https://developer.paddle.com/api-reference/notifications/overview

```python
class Notification(BaseModel):
    id: str
    type: str
    status: str
    payload: NotificationPayload
    occurred_at: datetime
    delivered_at: datetime | None
    replayed_at: str | None
    origin: str
    last_attempt_at: datetime | None
    retry_at: str | None
    times_attempted: int
    notification_setting_id: str
```

### Environment

* OS: macOS
* Python version: 3.10

**Comment by bgervan** [comment]
Thanks for the report.

Fixed in https://github.com/websideproject/paddle-billing-client/releases/tag/v0.1.15

**Comment by archatas** [comment]
Thank you, bgervan!
