### ISSUE TITLE
Pydantic 2 support or alternative to work without it ?

### ISSUE THREAD

**Issue by ddorian** [websideproject/paddle-billing-client#195]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/bgervan/paddle-billing-client/issues?q=is%3Aissue).

## ❓ Question

Looks like you depend on https://github.com/mom1/api-client-pydantic/issues/273 for Pydantic 2 support.

Is there an alternative way?

**Comment by bgervan** [comment]
This package uses the pydantic for typing support, so there is no alternative, when they upgrade to pydantic v2 this package will be migrated to that too. 

If you make a PR for the api-client, that could speed up the process, but probably I will take a look too how hard to upgrade their package, I didn't check yet.

**Comment by bgervan** [comment]
As a fast resolution good enough. I can do this very same change quickly if they approve and merge it. You can ping me here in case it's merged.

**Comment by bgervan** [comment]
Released a new version with pydantic v2

https://github.com/websideproject/paddle-billing-client/releases/tag/v0.2.0

This was a massive change, so there could be small issues even though the high number of test cases. Feel free to let me know if there is any issue
