### ISSUE TITLE
Resuming a paused Subscription raises 400 Error: Bad Request

### ISSUE THREAD

**Issue by archatas** [websideproject/paddle-billing-client#197]
## 🐛 Bug Report

Similarly to #196, there is an error when resuming an already paused Subscription, because the `SubscriptionRequest()` produces many variables instead of empty body.

## 🔬 How To Reproduce

1. Pause a subscription with `effective_from="immediately"`
2. Try to resume it with `client.resume_subscription()`

### Code sample

```python
client.pause_subscription(
    subscription_id="sub_xxx",
    data=SubscriptionRequest(
        effective_from="immediately",
    ),
)
client.resume_subscription(
    subscription_id="sub_xxx",
    data=SubscriptionRequest(),
)
```

I can't find a correct workaround at the moment.

### Environment

* OS: macOS
* Python version: 3.10

**Comment by bgervan** [comment]
The resume endpoint requires the effective_from param.

https://developer.paddle.com/api-reference/subscriptions/resume-subscription

This seems to be a bug in their documentation here though: https://developer.paddle.com/build/subscriptions/pause-subscriptions#post-resume-subscription

**Comment by bgervan** [comment]
Btw, this was the endpoint which returned 500 for me. If the request is bad, it should return 400, as it returns now

subscription = self.client.resume_subscription(
            subscription_id="sub_01h7n3a88jwktex2tfjzahmn57",
            data=SubscriptionRequest(
                effective_from="immediately",
            )
        )

**Comment by bgervan** [comment]
Is it resolved?

**Comment by bgervan** [comment]
I was wrong probably, after updated to pydantic v2, I had seen this issue. 

I am forcing to exclude Nones now with the latest version (0.2.1)

**Comment by archatas** [comment]
Sorry for my late response. I am still testing the overall behaviour of my app and have to fix some issues before replying regarding the subscription resuming. I think it worked, but will tell for sure in the next couple of days.

**Comment by archatas** [comment]
I am still on 1.10.13, but I can test v2 too. I just need some more time to get there, as there are other projects I have to finish at first.

**Comment by archatas** [comment]
I upgraded paddle-billing-client and all dependencies and tested the issues.

Resuming a paused subscription works, but cancelling a paused subscription raises a 400 Error: Bad Request.

Cancelling an active subscription is alright.

**Comment by bgervan** [comment]
Thanks, I close this as resolved.
