### ISSUE TITLE
Cancelling a Subscription raise 400 Error: Bad Request

### ISSUE THREAD

**Issue by archatas** [websideproject/paddle-billing-client#198]
## 🐛 Bug Report

Similarly to #196, there is an error when cancelling a Subscription, probably because the `SubscriptionRequest()` produces many variables.

## 🔬 How To Reproduce

1. Try to cancel a subscription with `client.cancel_subscription()`

### Code sample

```python
client.cancel_subscription(
    subscription_id="sub_xxx",
    data=SubscriptionRequest(effective_from="immediately"),
)
```

I can't find a correct workaround at the moment.

### Environment

* OS: macOS
* Python version: 3.10

**Comment by bgervan** [comment]
It works just fine for me

```
subscription = self.client.cancel_subscription(
            subscription_id="sub_01h7n3a88jwktex2tfjzahmn57",
            data=SubscriptionRequest(
                effective_from="immediately",
            ),
        )
```

All the none values from the SubscriptionRequest are excluded from the request body, in this case this is the request body (read from the test recorded requests)
```
  request:
    body: '{"effective_from": "immediately"}'
```

**Comment by archatas** [comment]
Now I see. The error happens only when you try to cancel a paused Subscription.

**Comment by archatas** [comment]
This error still happens when you try to cancel a paused subscription. I tested that with a subscription that will be paused after the current billing cycle.

**Comment by bgervan** [comment]
You can check the response from paddle api via

```
client = PaddleApiClient(
    base_url="https://sandbox-api.paddle.com", 
    authentication_method=HeaderAuthentication(token="your-paddle-token"),
    error_handler=VerboseErrorHandler
)
```

What I get:
```
apiclient.exceptions.ClientError: 400 
Error: Bad Request for url: https://sandbox-api.paddle.com/subscriptions/.../cancel 
with raw data: {"error":{"type":"request_error","code":"subscription_locked_pending_changes","detail":"cannot update subscription, pending scheduled changes","documentation_url":"https://developer.paddle.com/v1/errors/subscriptions/subscription_locked_pending_changes"},"meta":{"request_id":"..."}}
```

So this is an issue with paddle workflow, but let me know if you get a different error.

**Comment by archatas** [comment]
I am having troubles accessing the sandbox dashboard at the moment. Will get back to you when that is fixed.

**Comment by archatas** [comment]
It seems the same error:

```
ClientError: 400 Error: Bad Request for url: https://sandbox-api.paddle.com/subscriptions/sub_01hm55h88n7wc4q4vtzmdrb9j0/cancelwith raw data: {"error":{"type":"request_error","code":"subscription_locked_pending_changes","detail":"cannot update subscription, pending scheduled changes","documentation_url":"https://developer.paddle.com/v1/errors/subscriptions/subscription_locked_pending_changes"},"meta":{"request_id":"4ed1d93c-f4cf-4636-989d-bd23c587740a"}}
```

So the workflow would be, at first to resume the subscription, and then cancel it, I guess.

**Comment by archatas** [comment]
It seems that calling `client.unschedule_pause_from_subscription()` before cancelling if there are any scheduled actions, works, but it sends two notification emails to the user.

For clarity, I would rename `client.unschedule_pause_from_subscription()` to `client.unschedule_scheduled_action_from_subscription()`, because the scheduled action can be either `pause` or `resume`, or `cancel`.

**Comment by bgervan** [comment]
Good idea, included in https://github.com/websideproject/paddle-billing-client/releases/tag/v0.2.4

You can follow up when you get an answer
