### ISSUE TITLE
Webhook authentication

### ISSUE THREAD

**Issue by ddorian** [websideproject/paddle-billing-client#201]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/bgervan/paddle-billing-client/issues?q=is%3Aissue).

## ❓ Have you done the webhook authentication on the new Paddle Billing?

Asking since I couldn't find it in the code or searching around.

Regards.
Dorian

**Comment by bgervan** [comment]
Do you mean the signature verification?
https://developer.paddle.com/webhooks/signature-verification

**Comment by ddorian** [comment]
@bgervan Yes. All other libraries have the old "Classic" method with "p_signature".

**Comment by bgervan** [comment]
This is part of the django side, as that processes the request. I can share my first implementation, though I didn't test it yet and not that clean yet.

```
def webhook_signature_is_valid(request):
    secret_key = settings.PADDLE_SECRET_KEY
    # Get the Paddle-Signature header from an incoming webhook sent by Paddle.
    signature_header = request.META.get('HTTP_PADDLE_SIGNATURE', '')
    # signature = ts=1671552777;h1=somerandomstring
    # Now you have the Paddle-Signature header, parse it to extract the timestamp (ts) and signature values (h1).
    # The timestamp and signature are separated by a semicolon (;).
    timestamp, signature = signature_header.split(';')

    # Concatenate the timestamp and the raw body of the request, joined with a colon (:).
    signed_payload = ':'.join([timestamp, request.body.decode('utf-8')])
    # Paddle generates signatures using a keyed-hash message authentication code (HMAC) with SHA256 and a secret key.

    import hmac
    import hashlib
    computed_signature = hmac.new(
        key=secret_key.encode('utf-8'),
        msg=signed_payload.encode('utf-8'),
        digestmod=hashlib.sha256
    ).hexdigest()
    # Compare the computed signature with the signature extracted from the Paddle-Signature header.
    return hmac.compare_digest(computed_signature, signature)
```

You can expose your django local with cloudflare tunnel for free to test this implementation.

**Comment by ddorian** [comment]
@bgervan 

It had a small error on not removing "=". Fixed it (also removed the django parts)

```python
def webhook_signature_is_valid(signature_header: str, raw_body: bytes, secret_key: str) -> bool:
    # Get the Paddle-Signature header from an incoming webhook sent by Paddle.
    # signature_header = request.META.get('HTTP_PADDLE_SIGNATURE', '')
    # signature = ts=1671552777;h1=somerandomstring
    # Now you have the Paddle-Signature header, parse it to extract the timestamp (ts) and signature values (h1).
    # The timestamp and signature are separated by a semicolon (;).
    ts_part, h1_part = signature_header.split(";")
    var, timestamp = ts_part.split("=")
    var, signature = h1_part.split("=")

    # Concatenate the timestamp and the raw body of the request, joined with a colon (:).
    signed_payload = ":".join([timestamp, raw_body.decode("utf-8")])
    # Paddle generates signatures using a keyed-hash message authentication code (HMAC) with SHA256 and a secret key.

    import hashlib
    import hmac

    computed_signature = hmac.new(
        key=secret_key.encode("utf-8"), msg=signed_payload.encode("utf-8"), digestmod=hashlib.sha256
    ).hexdigest()
    # Compare the computed signature with the signature extracted from the Paddle-Signature header.
    return hmac.compare_digest(computed_signature, signature)
```

**Comment by bgervan** [comment]
I have included this function in https://github.com/websideproject/paddle-billing-client/releases/tag/v0.2.0 as a helper function

**Comment by aditodkar** [comment]
@bgervan How are you testing webhook events against new paddle billing authentication? I am sending test events through this link: https://sandbox-vendors.paddle.com/webhook-alert-test but I see that `Paddle-Signature` header is missing. Any suggestions?

**Comment by bgervan** [comment]
You can see an example in the my django integration package:
https://github.com/websideproject/django-paddle-billing/blob/437ae409e37963c0fdb4c845c344bb77742bad06/src/django_paddle_billing/views.py#L85C20-L85C46

**Comment by bgervan** [comment]
Although I checked with your link, I don't see this header. I am using my backend with real webhooks, not the test webhooks which works.
In the readme, you can find doc about how to expose your local dev server to receive webhook events securely.

**Comment by aditodkar** [comment]
> Although I checked with your link, I don't see this header. I am using my backend with real webhooks, not the test webhooks which works. In the readme, you can find doc about how to expose your local dev server to receive webhook events securely.

I have resolved the issue. Actually this [link](https://sandbox-vendors.paddle.com/webhook-alert-test) only works for paddle classic version. For new paddle billing APIs there is paddle-signature header present in webhook event.
