### ISSUE TITLE
Nicer pydantic version dependency

### ISSUE THREAD

**Issue by ddorian** [websideproject/paddle-billing-client#207]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/bgervan/paddle-billing-client/issues?q=is%3Aissue).

## ❓ Question

In https://github.com/websideproject/paddle-billing-client/blob/main/requirements.txt#L8, it's better to use a broader version like in https://github.com/mom1/api-client-pydantic/blob/main/pyproject.toml#L32.

This makes it possible to continue upgrading pedantic.

Regards

**Comment by bgervan** [comment]
The requirements.txt is not used during the install of this package, that is an internal file.

This file matters:
https://github.com/websideproject/paddle-billing-client/blob/3b5831fff09f1cad118ddba0d93d9e9f92f9a3ab/pyproject.toml#L37

This package has no direct dep for pydantic, only for api-client-pydantic.

Do you observe any issue during the install?

**Comment by ddorian** [comment]
Then it should be something else. Thank you.
