### ISSUE TITLE
CustomerQueryParams missing 'email' field

### ISSUE THREAD

**Issue by kontur** [websideproject/paddle-billing-client#211]
## 🐛 Bug Report

The [API](https://developer.paddle.com/api-reference/customers/list-customers#query-parameters) for customer query parameters lists `email` as unique key search for a customer. This parameter is now allowed in the client [CustomerQueryParams](https://github.com/websideproject/paddle-billing-client/blob/c8398d6b75cb9ed18b590379594f8b4d16e098cb/paddle_billing_client/models/customer.py#L34)

## 🔬 How To Reproduce / Code sample

```
client = PaddleApiClient(...)
client.list_customer(CustomerQueryParams(email="johndoe@example.com")
```

Will result in:

> 1 validation error for CustomerQueryParams email Extra inputs are not permitted [type=extra_forbidden, input_value='johndoe@example.com', input_type=str] For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden

### Environment

* OS: macOs
* Python version: 3.10.7
* Library version: 0.2.1

## 📈 Expected behavior

I'd expect it to call the API as described in the API docs. :)

**Comment by bgervan** [comment]
Thanks for the report, fixed in
https://github.com/websideproject/paddle-billing-client/releases/tag/v0.2.2

**Comment by kontur** [comment]
That was fast, merci :)
