### ISSUE TITLE
email is required in CustomerRequest, causes validation error, when updating other fields

### ISSUE THREAD

**Issue by Vincent17201** [websideproject/paddle-billing-client#252]
## 🐛 Bug Report

When I want to update an attribute (for example: custom_data or the name) of a customer with update_customer I get an pydantic validation error. Caused by CustomerRequest which inherits from CustomerBase where email is required. I guess this is not optimal and could be error-prone when updating fields other than email, but have to update email every time with it.

```
1 validation error for update_customer
data.email
  Field required [type=missing, input_value={'custom_data': {'user_id': 123}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
```

## 🔬 How To Reproduce

```
client = PaddleApiClient(...)
customer_id = "ctm_...."
data = {"custom_data": {"user_id": 123}}
response = client.update_customer(customer_id=customer_id, data=data)
 ```

### Environment

* OS: macOS
* Python version, get it with:

```bash
python --version  3.11.3
```

## 📈 Expected behavior

Update a customer attribute other than email without the need to update the email.

**Comment by bgervan** [comment]
Resolved in https://github.com/websideproject/paddle-billing-client/releases/tag/v0.2.6
