### ISSUE TITLE
Error in webhooks when creating a new Discount in paddle

### ISSUE THREAD

**Issue by bndr** [websideproject/paddle-billing-client#410]
## 🐛 Bug Report

ValidationError
1 validation error for Discount
times_used
  Field required [type=missing, input_value={'id': 'dsc_0xxxx...recurring_intervals': 3}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing

## 🔬 How To Reproduce

1. Create a discount
2. Wait for the webhook to sync discounts
3. times_used is marked as missing
4. I would expect that not to be an issue for a freshly created discount

<img width="583" alt="error_123" src="https://github.com/user-attachments/assets/d9403775-b1cf-407c-8228-a38cc54fff85">

**Comment by bgervan** [comment]
https://developer.paddle.com/api-reference/discounts/overview

<img width="809" alt="image" src="https://github.com/user-attachments/assets/47ec345b-71e6-4286-9db4-b9a1ede0be7e">

The times_used is not optional based on their doc, they should return 0. Which event type was it?

**Comment by bndr** [comment]
The event was discount.created. Attaching the screenshot from Sentry with the raw payload received.

<img width="599" alt="ValidationError: 1 validation error for Discount times_used Field required  type=missing, input_value={'id': 'dsc_01j4hdyshf3e2… 2024-08-06 14-12-31" src="https://github.com/user-attachments/assets/206aeeb3-2791-49de-a5c1-e69a0a52040f">

**Comment by bgervan** [comment]
This is a bug in their doc or in their system, but I made the required change.

Released with v0.2.12

Let me know if it solved your issue. You may need to specify the new version if you installed the paddle billing client through the django package, will update the deps there too

**Comment by bndr** [comment]
Thanks a lot. Appreciate the changes, I do use the Django package, and I just pull the repo directly, not through PyPi.
